version: '3'

services:
  atrocore:
    build:
      context: .
      dockerfile: Dockerfile_apache
    ports:
      - "80:80"

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: D4t4-Pl4yers
      MYSQL_DATABASE: atrocore
      MYSQL_USER: atrocore_user
      MYSQL_PASSWORD: atrocore_password
    ports:
      - "3306"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"